---
title: "QBS177_FINAL PROJECT"
author: "GROUP3"
date: "2/25/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This data set contains 31 clinical attributes, m-RNA levels z-score for 331 genes, and mutation in 175 genes for 1904 breast cancer patients. Here, we just used the clinical variables of the data set. Clinical attributes in the dataset have 31 variables. 
```{r}
RNA_Mutation<-read.csv("/Users/parinithakompala/Desktop/QBS177/METABRIC_RNA_Mutation.csv")#reading the data
```

```{r}
RNA_Mutation_updated<- RNA_Mutation[ -c(0,521:693) ] #removing all the mutation columns for better analysis purposes
```

```{r}
#(is.na(RNA_Mutation_updated))#checking for NA
str(RNA_Mutation_updated)
```



```{r}
#To replace “ ” with  NA
RNA_Mutation_updated[RNA_Mutation_updated == ""] <- NA  
```

```{r}
# To change character variables to factor 
RNA_Mutation_updated$type_of_breast_surgery <- as.factor(RNA_Mutation_updated$type_of_breast_surgery)
RNA_Mutation_updated$cellularity <- as.factor(RNA_Mutation_updated$cellularity); 
RNA_Mutation_updated$chemotherapy <- as.factor(RNA_Mutation_updated$chemotherapy)
RNA_Mutation_updated$pam50_._claudin.low_subtype <- as.factor(RNA_Mutation_updated$pam50_._claudin.low_subtype); 
RNA_Mutation_updated$er_status <- as.factor(RNA_Mutation_updated$er_status); 
RNA_Mutation_updated$neoplasm_histologic_grade <- as.factor(RNA_Mutation_updated$neoplasm_histologic_grade);
RNA_Mutation_updated$her2_status <- as.factor(RNA_Mutation_updated$her2_status);
RNA_Mutation_updated$tumor_other_histologic_subtype <- as.factor(RNA_Mutation_updated$tumor_other_histologic_subtype)
RNA_Mutation_updated$hormone_therapy <- as.factor(RNA_Mutation_updated$hormone_therapy);
RNA_Mutation_updated$inferred_menopausal_state<- as.factor(RNA_Mutation_updated$inferred_menopausal_state)
RNA_Mutation_updated$integrative_cluster<- as.factor(RNA_Mutation_updated$integrative_cluster ); 
RNA_Mutation_updated$primary_tumor_laterality<- as.factor(RNA_Mutation_updated$primary_tumor_laterality)
RNA_Mutation_updated$pr_status<- as.factor(RNA_Mutation_updated$pr_status); 
RNA_Mutation_updated$radio_therapy <- as.factor(RNA_Mutation_updated$radio_therapy)
RNA_Mutation_updated$overall_survival<- as.factor(RNA_Mutation_updated$overall_survival); 

```

```{r}
# exploring numeric data
# To remove Redundant  column
RNA_Mutation_updated$patient_id <- NULL        
RNA_Mutation_updated$cancer_type <- NULL       
RNA_Mutation_updated$death_from_cancer <- NULL  
RNA_Mutation_updated$cancer_type_detailed <- NULL  
RNA_Mutation_updated$oncotree_code <- NULL   
RNA_Mutation_updated$cohort <- NULL   
RNA_Mutation_updated$tumor_stage <- NULL
RNA_Mutation_updated$overall_survival_months  <- NULL
RNA_Mutation_updated$X3.gene_classifier_subtype  <- NULL
RNA_Mutation_updated$er_status_measured_by_ihc  <- NULL
RNA_Mutation_updated$her2_status_measured_by_snp6  <- NULL


clinical<-RNA_Mutation_updated[, c(1:20)]    # To make clinical data set
```

```{r}
library(visdat)

clinical %>% 
  visdat::vis_miss()
```


```{r}
clinical_n <- select_if(clinical, is.numeric) 
corrmatrix <- cor(clinical_n)

clinical <- na.omit(clinical)

corrmatrix <- cor(clinical_n)

corrplot::corrplot(corrmatrix, method="shade", type = "upper",tl.cex=.6	
, tl.col="black", title="Correlation Plot",number.font = 2, mar=c(0,0,1,0),	)
```
```{r}
library(ggformula)
clinical %>% gf_boxplot(age_at_diagnosis~overall_survival) %>%   
  gf_labs(x = "Survival",  
    y = "Age") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))


clinical %>% gf_boxplot(tumor_size~overall_survival) %>%   
  gf_labs(x = "Survival",  
    y = "Tumor size") %>%   
  gf_theme(axis.text = element_text(size = 12),
           axis.title = element_text(size = 12),
        legend.title=element_text(size=14), 
    legend.text=element_text(size=9))

```


```{r}
data.nona=RNA_Mutation_updated[complete.cases(RNA_Mutation_updated),] #delete all rows with any NA
genes=data.nona[,21:509] #subset gene columns
```


```{r}
#PCA analysis
pca=prcomp(genes,scale=TRUE)
#summary(pca)
```

```{r}
#install.packages("factoextra")
library(factoextra)
fviz_pca_ind(pca, geom.ind = "point", pointshape = 21, 
             pointsize = 2, 
             fill.ind = data.nona$overall_survival, 
             col.ind = "black", 
             palette = "jco", 
             addEllipses = TRUE,
             label = "var",
             col.var = "black",
             repel = TRUE,
             legend.title = "Diagnosis") +
  ggtitle("2D PCA-plot from 30 feature dataset") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
library(ggplot2)
screeplot(pca, type = "l", npcs = 100, main = "Screeplot of the first 100 PCs")
abline(h = 1, col="red", lty=5)
legend("topright", legend=c("Eigenvalue = 1"),
       col=c("red"), lty=5, cex=0.6)
cumpro <- cumsum(pca$sdev^2/sum(pca$sdev^2))
plot(cumpro[0:200], xlab = "PC #", ylab = "Amount of explained variance", main = "Cumulative variance plot")
abline(v = 100, col="blue", lty=5)
abline(h = 0.7, col="blue", lty=5)
legend("topleft", legend=c("Cut-off @ PC100"),
       col=c("blue"), lty=5, cex=0.6)
```

```{r}
comp=data.frame(pca$x[,1:100]) #retain the first 100 principal components
cluster.data=cbind(data.nona[,1:20],comp) #dataset for cluster analysis
```

```{r}
#Correlation distance with complete linkage: 
clust.cor.complete <- hclust(as.dist(1-cor(genes)),method="complete")
plot(clust.cor.complete)

```


```{r}
#Euclidean distance with average linkage: 
clust.euclid.average<- hclust(dist(t(genes)),method="average")
plot(clust.euclid.average)
```
 
```{r}
#uclidean distance with Ward’s method: 
clust.euclid.ward<- hclust(dist(t(LS)),method="ward")
plot(clust.euclid.ward)
```
```{r}
#Euclidean distance with average linkage: 
clust.euclid.average<- hclust(dist(genes),method="average")
plot(clust.euclid.average)
x<-cutree(clust.euclid.average,2)
table((clust.cor.complete),(cluster.data$overall_survival))

DF=cbind(cluster.data$overall_survival, cutree)
DF$precision=ifelse(cluster.data$overall_survival==cutree,1,0)
Mean(DF$precision)
```

